// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: bills.sql

package database

import (
	"context"
)

const createBill = `-- name: CreateBill :one
INSERT INTO bills (title, description, host_user_id)
VALUES (?1, ?2, ?3)
RETURNING id, host_user_id, title, description
`

type CreateBillParams struct {
	Title       string
	Description string
	HostUserID  int64
}

func (q *Queries) CreateBill(ctx context.Context, arg CreateBillParams) (Bill, error) {
	row := q.db.QueryRowContext(ctx, createBill, arg.Title, arg.Description, arg.HostUserID)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.HostUserID,
		&i.Title,
		&i.Description,
	)
	return i, err
}

const getBillDetail = `-- name: GetBillDetail :one
SELECT
    b.id,
    b.title,
    b.description,
    b.host_user_id,
    u.full_name AS user_full_name
FROM bills b
JOIN users u ON host_user_id = ?1
WHERE b.id = ?1
`

type GetBillDetailRow struct {
	ID           int64
	Title        string
	Description  string
	HostUserID   int64
	UserFullName string
}

func (q *Queries) GetBillDetail(ctx context.Context, userID int64) (GetBillDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getBillDetail, userID)
	var i GetBillDetailRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.HostUserID,
		&i.UserFullName,
	)
	return i, err
}

const getBillsByUser = `-- name: GetBillsByUser :many
SELECT
    id,
    title,
    description,
    (b.host_user_id = ?1) AS is_host
FROM bills b
WHERE host_user_id = ?1
OR :user_id IN (
    SELECT user_id FROM participants
    WHERE bill_id = b.id
)
`

type GetBillsByUserRow struct {
	ID          int64
	Title       string
	Description string
	IsHost      interface{}
}

func (q *Queries) GetBillsByUser(ctx context.Context, userID int64) ([]GetBillsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getBillsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBillsByUserRow
	for rows.Next() {
		var i GetBillsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.IsHost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
