// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"database/sql"
)

type Bill struct {
	ID          int64
	HostUserID  int64
	Title       string
	Description string
}

type Item struct {
	ID         int64
	Name       string
	Price      float64
	InitialQty int64
}

type Order struct {
	ID            int64
	ParticipantID int64
	ItemID        int64
	Qty           interface{}
}

type Participant struct {
	ID            int64
	BillID        int64
	UserID        int64
	JoinedAt      interface{}
	PaymentStatus sql.NullBool
}

type User struct {
	ID       int64
	FullName string
	Email    string
	Password string
}
