// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"database/sql"
)

type Bill struct {
	ID          int64  `json:"id"`
	HostUserID  int64  `json:"host_user_id"`
	Code        string `json:"code"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

type Item struct {
	ID         int64   `json:"id"`
	BillID     int64   `json:"bill_id"`
	Name       string  `json:"name"`
	Price      float64 `json:"price"`
	InitialQty int64   `json:"initial_qty"`
}

type Order struct {
	ID            int64 `json:"id"`
	ParticipantID int64 `json:"participant_id"`
	ItemID        int64 `json:"item_id"`
	Qty           int64 `json:"qty"`
}

type Participant struct {
	ID            int64        `json:"id"`
	BillID        int64        `json:"bill_id"`
	UserID        int64        `json:"user_id"`
	JoinedAt      int64        `json:"joined_at"`
	PaymentStatus sql.NullBool `json:"payment_status"`
}

type User struct {
	ID       int64  `json:"id"`
	FullName string `json:"full_name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
