// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"context"
)

type Querier interface {
	AddItemToBill(ctx context.Context, arg AddItemToBillParams) (Item, error)
	AddParticipantToBill(ctx context.Context, arg AddParticipantToBillParams) (Participant, error)
	CreateBill(ctx context.Context, arg CreateBillParams) (Bill, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetBillDetail(ctx context.Context, code string) (GetBillDetailRow, error)
	GetBillItems(ctx context.Context, billID int64) ([]Item, error)
	GetBillParticipants(ctx context.Context, billID int64) ([]GetBillParticipantsRow, error)
	GetBillsByUser(ctx context.Context, userID int64) ([]GetBillsByUserRow, error)
	GetParticipantOrders(ctx context.Context, participantIds []int64) ([]Order, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	UpdateItemAtBill(ctx context.Context, arg UpdateItemAtBillParams) (Item, error)
}

var _ Querier = (*Queries)(nil)
